# Generated by Django 3.2.2 on 2021-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('advisor_id', models.IntegerField()),
                ('date', models.TimeField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='registeruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
