# Generated by Django 3.2.2 on 2021-05-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210513_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookadvisor',
            old_name='time',
            new_name='booking_time',
        ),
    ]
