# Generated by Django 3.2.2 on 2021-05-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_time_bookadvisor_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookadvisor',
            old_name='booking_time',
            new_name='time',
        ),
    ]
